In [ ]:
import numpy

In [3]:
import numpy

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])

In [6]:
print(a)

[1 2 3]


In [9]:
c = np.array([(1,2,3),(4,5,6)])

In [10]:
print(c)

[[1 2 3]
 [4 5 6]]


In [12]:
kathu = np.transpose(c)

In [13]:
print(kathu)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
kathu.ravel()

array([1, 4, 2, 5, 3, 6])

In [18]:
c.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
c.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [23]:
ze=np.zeros((1,1))

In [24]:
print(ze)

[[0.]]


In [25]:
za=np.zeros((10,12))

In [26]:
print(za)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [27]:
zb=np.ones((12,24))

In [28]:
print(zb)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [29]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [30]:
np.random.random((12,24))

array([[0.0920693 , 0.27404628, 0.80900476, 0.98343131, 0.80482757,
        0.9915167 , 0.47685385, 0.98472215, 0.59301104, 0.69098973,
        0.02368791, 0.67679765, 0.66263214, 0.61137602, 0.69883014,
        0.17994185, 0.63684193, 0.62638649, 0.73493086, 0.69070829,
        0.7276484 , 0.76410344, 0.16448285, 0.32284008],
       [0.75128701, 0.33381773, 0.49940365, 0.99899663, 0.32808452,
        0.9483993 , 0.25851357, 0.63252145, 0.30030174, 0.0515761 ,
        0.91820489, 0.14495484, 0.5787022 , 0.9118866 , 0.04153396,
        0.2786599 , 0.77634738, 0.03716337, 0.28024819, 0.0325188 ,
        0.29332131, 0.38596457, 0.29209312, 0.04687409],
       [0.85108661, 0.42546562, 0.44666743, 0.55414072, 0.52076979,
        0.45452782, 0.95326968, 0.18268831, 0.88549631, 0.43937936,
        0.34780852, 0.67261586, 0.32958127, 0.15131561, 0.37587379,
        0.32851567, 0.33206852, 0.17953111, 0.78300708, 0.52792166,
        0.9125089 , 0.2102269 , 0.91918289, 0.79337412],
       [0.366